# Sample App Deployment

## Step 1: Save Deployment Manifest

Copy the following YAML content to a file named `deploy.yaml`:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-sample-linux-deployment
  labels:
    app: eks-sample-linux-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: eks-sample-linux-app
  template:
    metadata:
      labels:
        app: eks-sample-linux-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/arch
                    operator: In
                    values:
                      - amd64
                      - arm64
      containers:
        - name: nginx
          image: public.ecr.aws/nginx/nginx:1.23
          ports:
            - name: http
              containerPort: 80
          imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/os: linux
````

## Step 2: Deploy the Application

Run the following command to deploy the application:

```bash
kubectl apply -f deploy.yaml
```

---

## Step 3: Save Service Manifest

Copy the following YAML content to a file named `service.yaml`:

```yaml
apiVersion: v1
kind: Service
metadata:
  name: eks-sample-linux-service
  labels:
    app: eks-sample-linux-app
spec:
  selector:
    app: eks-sample-linux-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
```

## Step 4: Deploy the Service

Run the following command to deploy the service:

```bash
kubectl apply -f service.yaml
```

```

This format is structured with clear step titles, consistent indentation, and easy-to-follow instructions — perfect for your README or documentation.
```
